<?php
/**
 * TransformsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * TransformsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransformsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'endpointsEndpointIdTransformsGet' => [
            'application/json',
        ],
        'endpointsEndpointIdTransformsIdDelete' => [
            'application/json',
        ],
        'endpointsEndpointIdTransformsIdPut' => [
            'application/json',
        ],
        'endpointsEndpointIdTransformsPost' => [
            'application/json',
        ],
        'endpointsEndpointIdTransformsTestPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation endpointsEndpointIdTransformsGet
     *
     * List transform rules for endpoint
     *
     * @param  string $endpoint_id endpoint_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\TransformRule[]
     */
    public function endpointsEndpointIdTransformsGet($endpoint_id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsGet'][0])
    {
        list($response) = $this->endpointsEndpointIdTransformsGetWithHttpInfo($endpoint_id, $contentType);
        return $response;
    }

    /**
     * Operation endpointsEndpointIdTransformsGetWithHttpInfo
     *
     * List transform rules for endpoint
     *
     * @param  string $endpoint_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\TransformRule[], HTTP status code, HTTP response headers (array of strings)
     */
    public function endpointsEndpointIdTransformsGetWithHttpInfo($endpoint_id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsGet'][0])
    {
        $request = $this->endpointsEndpointIdTransformsGetRequest($endpoint_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\TransformRule[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\TransformRule[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\TransformRule[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation endpointsEndpointIdTransformsGetAsync
     *
     * List transform rules for endpoint
     *
     * @param  string $endpoint_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsGetAsync($endpoint_id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsGet'][0])
    {
        return $this->endpointsEndpointIdTransformsGetAsyncWithHttpInfo($endpoint_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation endpointsEndpointIdTransformsGetAsyncWithHttpInfo
     *
     * List transform rules for endpoint
     *
     * @param  string $endpoint_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsGetAsyncWithHttpInfo($endpoint_id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\TransformRule[]';
        $request = $this->endpointsEndpointIdTransformsGetRequest($endpoint_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'endpointsEndpointIdTransformsGet'
     *
     * @param  string $endpoint_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function endpointsEndpointIdTransformsGetRequest($endpoint_id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsGet'][0])
    {

        // verify the required parameter 'endpoint_id' is set
        if ($endpoint_id === null || (is_array($endpoint_id) && count($endpoint_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $endpoint_id when calling endpointsEndpointIdTransformsGet'
            );
        }


        $resourcePath = '/endpoints/{endpoint_id}/transforms';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($endpoint_id !== null) {
            $resourcePath = str_replace(
                '{endpoint_id}',
                ObjectSerializer::toPathValue($endpoint_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation endpointsEndpointIdTransformsIdDelete
     *
     * Delete transform rule
     *
     * @param  string $endpoint_id endpoint_id (required)
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function endpointsEndpointIdTransformsIdDelete($endpoint_id, $id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdDelete'][0])
    {
        $this->endpointsEndpointIdTransformsIdDeleteWithHttpInfo($endpoint_id, $id, $contentType);
    }

    /**
     * Operation endpointsEndpointIdTransformsIdDeleteWithHttpInfo
     *
     * Delete transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function endpointsEndpointIdTransformsIdDeleteWithHttpInfo($endpoint_id, $id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdDelete'][0])
    {
        $request = $this->endpointsEndpointIdTransformsIdDeleteRequest($endpoint_id, $id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation endpointsEndpointIdTransformsIdDeleteAsync
     *
     * Delete transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsIdDeleteAsync($endpoint_id, $id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdDelete'][0])
    {
        return $this->endpointsEndpointIdTransformsIdDeleteAsyncWithHttpInfo($endpoint_id, $id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation endpointsEndpointIdTransformsIdDeleteAsyncWithHttpInfo
     *
     * Delete transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsIdDeleteAsyncWithHttpInfo($endpoint_id, $id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdDelete'][0])
    {
        $returnType = '';
        $request = $this->endpointsEndpointIdTransformsIdDeleteRequest($endpoint_id, $id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'endpointsEndpointIdTransformsIdDelete'
     *
     * @param  string $endpoint_id (required)
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function endpointsEndpointIdTransformsIdDeleteRequest($endpoint_id, $id, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdDelete'][0])
    {

        // verify the required parameter 'endpoint_id' is set
        if ($endpoint_id === null || (is_array($endpoint_id) && count($endpoint_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $endpoint_id when calling endpointsEndpointIdTransformsIdDelete'
            );
        }

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling endpointsEndpointIdTransformsIdDelete'
            );
        }


        $resourcePath = '/endpoints/{endpoint_id}/transforms/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($endpoint_id !== null) {
            $resourcePath = str_replace(
                '{endpoint_id}',
                ObjectSerializer::toPathValue($endpoint_id),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation endpointsEndpointIdTransformsIdPut
     *
     * Update transform rule
     *
     * @param  string $endpoint_id endpoint_id (required)
     * @param  string $id id (required)
     * @param  object $body body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\TransformRule
     */
    public function endpointsEndpointIdTransformsIdPut($endpoint_id, $id, $body, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdPut'][0])
    {
        list($response) = $this->endpointsEndpointIdTransformsIdPutWithHttpInfo($endpoint_id, $id, $body, $contentType);
        return $response;
    }

    /**
     * Operation endpointsEndpointIdTransformsIdPutWithHttpInfo
     *
     * Update transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  string $id (required)
     * @param  object $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\TransformRule, HTTP status code, HTTP response headers (array of strings)
     */
    public function endpointsEndpointIdTransformsIdPutWithHttpInfo($endpoint_id, $id, $body, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdPut'][0])
    {
        $request = $this->endpointsEndpointIdTransformsIdPutRequest($endpoint_id, $id, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\TransformRule',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\TransformRule',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\TransformRule',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation endpointsEndpointIdTransformsIdPutAsync
     *
     * Update transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  string $id (required)
     * @param  object $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsIdPutAsync($endpoint_id, $id, $body, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdPut'][0])
    {
        return $this->endpointsEndpointIdTransformsIdPutAsyncWithHttpInfo($endpoint_id, $id, $body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation endpointsEndpointIdTransformsIdPutAsyncWithHttpInfo
     *
     * Update transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  string $id (required)
     * @param  object $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsIdPutAsyncWithHttpInfo($endpoint_id, $id, $body, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdPut'][0])
    {
        $returnType = '\OpenAPI\Client\Model\TransformRule';
        $request = $this->endpointsEndpointIdTransformsIdPutRequest($endpoint_id, $id, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'endpointsEndpointIdTransformsIdPut'
     *
     * @param  string $endpoint_id (required)
     * @param  string $id (required)
     * @param  object $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function endpointsEndpointIdTransformsIdPutRequest($endpoint_id, $id, $body, string $contentType = self::contentTypes['endpointsEndpointIdTransformsIdPut'][0])
    {

        // verify the required parameter 'endpoint_id' is set
        if ($endpoint_id === null || (is_array($endpoint_id) && count($endpoint_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $endpoint_id when calling endpointsEndpointIdTransformsIdPut'
            );
        }

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling endpointsEndpointIdTransformsIdPut'
            );
        }

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling endpointsEndpointIdTransformsIdPut'
            );
        }


        $resourcePath = '/endpoints/{endpoint_id}/transforms/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($endpoint_id !== null) {
            $resourcePath = str_replace(
                '{endpoint_id}',
                ObjectSerializer::toPathValue($endpoint_id),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation endpointsEndpointIdTransformsPost
     *
     * Create transform rule
     *
     * @param  string $endpoint_id endpoint_id (required)
     * @param  \OpenAPI\Client\Model\CreateTransformRuleRequest $create_transform_rule_request create_transform_rule_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\TransformRule
     */
    public function endpointsEndpointIdTransformsPost($endpoint_id, $create_transform_rule_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsPost'][0])
    {
        list($response) = $this->endpointsEndpointIdTransformsPostWithHttpInfo($endpoint_id, $create_transform_rule_request, $contentType);
        return $response;
    }

    /**
     * Operation endpointsEndpointIdTransformsPostWithHttpInfo
     *
     * Create transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  \OpenAPI\Client\Model\CreateTransformRuleRequest $create_transform_rule_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\TransformRule, HTTP status code, HTTP response headers (array of strings)
     */
    public function endpointsEndpointIdTransformsPostWithHttpInfo($endpoint_id, $create_transform_rule_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsPost'][0])
    {
        $request = $this->endpointsEndpointIdTransformsPostRequest($endpoint_id, $create_transform_rule_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\TransformRule',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\TransformRule',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\TransformRule',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation endpointsEndpointIdTransformsPostAsync
     *
     * Create transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  \OpenAPI\Client\Model\CreateTransformRuleRequest $create_transform_rule_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsPostAsync($endpoint_id, $create_transform_rule_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsPost'][0])
    {
        return $this->endpointsEndpointIdTransformsPostAsyncWithHttpInfo($endpoint_id, $create_transform_rule_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation endpointsEndpointIdTransformsPostAsyncWithHttpInfo
     *
     * Create transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  \OpenAPI\Client\Model\CreateTransformRuleRequest $create_transform_rule_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsPostAsyncWithHttpInfo($endpoint_id, $create_transform_rule_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\TransformRule';
        $request = $this->endpointsEndpointIdTransformsPostRequest($endpoint_id, $create_transform_rule_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'endpointsEndpointIdTransformsPost'
     *
     * @param  string $endpoint_id (required)
     * @param  \OpenAPI\Client\Model\CreateTransformRuleRequest $create_transform_rule_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function endpointsEndpointIdTransformsPostRequest($endpoint_id, $create_transform_rule_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsPost'][0])
    {

        // verify the required parameter 'endpoint_id' is set
        if ($endpoint_id === null || (is_array($endpoint_id) && count($endpoint_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $endpoint_id when calling endpointsEndpointIdTransformsPost'
            );
        }

        // verify the required parameter 'create_transform_rule_request' is set
        if ($create_transform_rule_request === null || (is_array($create_transform_rule_request) && count($create_transform_rule_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_transform_rule_request when calling endpointsEndpointIdTransformsPost'
            );
        }


        $resourcePath = '/endpoints/{endpoint_id}/transforms';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($endpoint_id !== null) {
            $resourcePath = str_replace(
                '{endpoint_id}',
                ObjectSerializer::toPathValue($endpoint_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_transform_rule_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_transform_rule_request));
            } else {
                $httpBody = $create_transform_rule_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation endpointsEndpointIdTransformsTestPost
     *
     * Test a transform rule
     *
     * @param  string $endpoint_id endpoint_id (required)
     * @param  \OpenAPI\Client\Model\EndpointsEndpointIdTransformsTestPostRequest $endpoints_endpoint_id_transforms_test_post_request endpoints_endpoint_id_transforms_test_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsTestPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function endpointsEndpointIdTransformsTestPost($endpoint_id, $endpoints_endpoint_id_transforms_test_post_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsTestPost'][0])
    {
        $this->endpointsEndpointIdTransformsTestPostWithHttpInfo($endpoint_id, $endpoints_endpoint_id_transforms_test_post_request, $contentType);
    }

    /**
     * Operation endpointsEndpointIdTransformsTestPostWithHttpInfo
     *
     * Test a transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  \OpenAPI\Client\Model\EndpointsEndpointIdTransformsTestPostRequest $endpoints_endpoint_id_transforms_test_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsTestPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function endpointsEndpointIdTransformsTestPostWithHttpInfo($endpoint_id, $endpoints_endpoint_id_transforms_test_post_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsTestPost'][0])
    {
        $request = $this->endpointsEndpointIdTransformsTestPostRequest($endpoint_id, $endpoints_endpoint_id_transforms_test_post_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation endpointsEndpointIdTransformsTestPostAsync
     *
     * Test a transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  \OpenAPI\Client\Model\EndpointsEndpointIdTransformsTestPostRequest $endpoints_endpoint_id_transforms_test_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsTestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsTestPostAsync($endpoint_id, $endpoints_endpoint_id_transforms_test_post_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsTestPost'][0])
    {
        return $this->endpointsEndpointIdTransformsTestPostAsyncWithHttpInfo($endpoint_id, $endpoints_endpoint_id_transforms_test_post_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation endpointsEndpointIdTransformsTestPostAsyncWithHttpInfo
     *
     * Test a transform rule
     *
     * @param  string $endpoint_id (required)
     * @param  \OpenAPI\Client\Model\EndpointsEndpointIdTransformsTestPostRequest $endpoints_endpoint_id_transforms_test_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsTestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function endpointsEndpointIdTransformsTestPostAsyncWithHttpInfo($endpoint_id, $endpoints_endpoint_id_transforms_test_post_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsTestPost'][0])
    {
        $returnType = '';
        $request = $this->endpointsEndpointIdTransformsTestPostRequest($endpoint_id, $endpoints_endpoint_id_transforms_test_post_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'endpointsEndpointIdTransformsTestPost'
     *
     * @param  string $endpoint_id (required)
     * @param  \OpenAPI\Client\Model\EndpointsEndpointIdTransformsTestPostRequest $endpoints_endpoint_id_transforms_test_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['endpointsEndpointIdTransformsTestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function endpointsEndpointIdTransformsTestPostRequest($endpoint_id, $endpoints_endpoint_id_transforms_test_post_request, string $contentType = self::contentTypes['endpointsEndpointIdTransformsTestPost'][0])
    {

        // verify the required parameter 'endpoint_id' is set
        if ($endpoint_id === null || (is_array($endpoint_id) && count($endpoint_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $endpoint_id when calling endpointsEndpointIdTransformsTestPost'
            );
        }

        // verify the required parameter 'endpoints_endpoint_id_transforms_test_post_request' is set
        if ($endpoints_endpoint_id_transforms_test_post_request === null || (is_array($endpoints_endpoint_id_transforms_test_post_request) && count($endpoints_endpoint_id_transforms_test_post_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $endpoints_endpoint_id_transforms_test_post_request when calling endpointsEndpointIdTransformsTestPost'
            );
        }


        $resourcePath = '/endpoints/{endpoint_id}/transforms/test';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($endpoint_id !== null) {
            $resourcePath = str_replace(
                '{endpoint_id}',
                ObjectSerializer::toPathValue($endpoint_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($endpoints_endpoint_id_transforms_test_post_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($endpoints_endpoint_id_transforms_test_post_request));
            } else {
                $httpBody = $endpoints_endpoint_id_transforms_test_post_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
