<?php
/**
 * UsageResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * UsageResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UsageResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'UsageResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'plan' => 'string',
        'period_start' => '\DateTime',
        'period_end' => '\DateTime',
        'webhooks_used' => 'int',
        'webhooks_limit' => 'int',
        'endpoints_used' => 'int',
        'endpoints_limit' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'plan' => null,
        'period_start' => 'date-time',
        'period_end' => 'date-time',
        'webhooks_used' => null,
        'webhooks_limit' => null,
        'endpoints_used' => null,
        'endpoints_limit' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'plan' => false,
        'period_start' => false,
        'period_end' => false,
        'webhooks_used' => false,
        'webhooks_limit' => false,
        'endpoints_used' => false,
        'endpoints_limit' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'plan' => 'plan',
        'period_start' => 'period_start',
        'period_end' => 'period_end',
        'webhooks_used' => 'webhooks_used',
        'webhooks_limit' => 'webhooks_limit',
        'endpoints_used' => 'endpoints_used',
        'endpoints_limit' => 'endpoints_limit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'plan' => 'setPlan',
        'period_start' => 'setPeriodStart',
        'period_end' => 'setPeriodEnd',
        'webhooks_used' => 'setWebhooksUsed',
        'webhooks_limit' => 'setWebhooksLimit',
        'endpoints_used' => 'setEndpointsUsed',
        'endpoints_limit' => 'setEndpointsLimit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'plan' => 'getPlan',
        'period_start' => 'getPeriodStart',
        'period_end' => 'getPeriodEnd',
        'webhooks_used' => 'getWebhooksUsed',
        'webhooks_limit' => 'getWebhooksLimit',
        'endpoints_used' => 'getEndpointsUsed',
        'endpoints_limit' => 'getEndpointsLimit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('plan', $data ?? [], null);
        $this->setIfExists('period_start', $data ?? [], null);
        $this->setIfExists('period_end', $data ?? [], null);
        $this->setIfExists('webhooks_used', $data ?? [], null);
        $this->setIfExists('webhooks_limit', $data ?? [], null);
        $this->setIfExists('endpoints_used', $data ?? [], null);
        $this->setIfExists('endpoints_limit', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['plan'] === null) {
            $invalidProperties[] = "'plan' can't be null";
        }
        if ($this->container['period_start'] === null) {
            $invalidProperties[] = "'period_start' can't be null";
        }
        if ($this->container['period_end'] === null) {
            $invalidProperties[] = "'period_end' can't be null";
        }
        if ($this->container['webhooks_used'] === null) {
            $invalidProperties[] = "'webhooks_used' can't be null";
        }
        if ($this->container['webhooks_limit'] === null) {
            $invalidProperties[] = "'webhooks_limit' can't be null";
        }
        if ($this->container['endpoints_used'] === null) {
            $invalidProperties[] = "'endpoints_used' can't be null";
        }
        if ($this->container['endpoints_limit'] === null) {
            $invalidProperties[] = "'endpoints_limit' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets plan
     *
     * @return string
     */
    public function getPlan()
    {
        return $this->container['plan'];
    }

    /**
     * Sets plan
     *
     * @param string $plan plan
     *
     * @return self
     */
    public function setPlan($plan)
    {
        if (is_null($plan)) {
            throw new \InvalidArgumentException('non-nullable plan cannot be null');
        }
        $this->container['plan'] = $plan;

        return $this;
    }

    /**
     * Gets period_start
     *
     * @return \DateTime
     */
    public function getPeriodStart()
    {
        return $this->container['period_start'];
    }

    /**
     * Sets period_start
     *
     * @param \DateTime $period_start period_start
     *
     * @return self
     */
    public function setPeriodStart($period_start)
    {
        if (is_null($period_start)) {
            throw new \InvalidArgumentException('non-nullable period_start cannot be null');
        }
        $this->container['period_start'] = $period_start;

        return $this;
    }

    /**
     * Gets period_end
     *
     * @return \DateTime
     */
    public function getPeriodEnd()
    {
        return $this->container['period_end'];
    }

    /**
     * Sets period_end
     *
     * @param \DateTime $period_end period_end
     *
     * @return self
     */
    public function setPeriodEnd($period_end)
    {
        if (is_null($period_end)) {
            throw new \InvalidArgumentException('non-nullable period_end cannot be null');
        }
        $this->container['period_end'] = $period_end;

        return $this;
    }

    /**
     * Gets webhooks_used
     *
     * @return int
     */
    public function getWebhooksUsed()
    {
        return $this->container['webhooks_used'];
    }

    /**
     * Sets webhooks_used
     *
     * @param int $webhooks_used webhooks_used
     *
     * @return self
     */
    public function setWebhooksUsed($webhooks_used)
    {
        if (is_null($webhooks_used)) {
            throw new \InvalidArgumentException('non-nullable webhooks_used cannot be null');
        }
        $this->container['webhooks_used'] = $webhooks_used;

        return $this;
    }

    /**
     * Gets webhooks_limit
     *
     * @return int
     */
    public function getWebhooksLimit()
    {
        return $this->container['webhooks_limit'];
    }

    /**
     * Sets webhooks_limit
     *
     * @param int $webhooks_limit webhooks_limit
     *
     * @return self
     */
    public function setWebhooksLimit($webhooks_limit)
    {
        if (is_null($webhooks_limit)) {
            throw new \InvalidArgumentException('non-nullable webhooks_limit cannot be null');
        }
        $this->container['webhooks_limit'] = $webhooks_limit;

        return $this;
    }

    /**
     * Gets endpoints_used
     *
     * @return int
     */
    public function getEndpointsUsed()
    {
        return $this->container['endpoints_used'];
    }

    /**
     * Sets endpoints_used
     *
     * @param int $endpoints_used endpoints_used
     *
     * @return self
     */
    public function setEndpointsUsed($endpoints_used)
    {
        if (is_null($endpoints_used)) {
            throw new \InvalidArgumentException('non-nullable endpoints_used cannot be null');
        }
        $this->container['endpoints_used'] = $endpoints_used;

        return $this;
    }

    /**
     * Gets endpoints_limit
     *
     * @return int
     */
    public function getEndpointsLimit()
    {
        return $this->container['endpoints_limit'];
    }

    /**
     * Sets endpoints_limit
     *
     * @param int $endpoints_limit endpoints_limit
     *
     * @return self
     */
    public function setEndpointsLimit($endpoints_limit)
    {
        if (is_null($endpoints_limit)) {
            throw new \InvalidArgumentException('non-nullable endpoints_limit cannot be null');
        }
        $this->container['endpoints_limit'] = $endpoints_limit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


